//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONVANCHUYEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONVANCHUYEN()
        {
            this.HANGHOAs = new HashSet<HANGHOA>();
            this.VANCHUYENs = new HashSet<VANCHUYEN>();
            this.DVC_VOUCHER = new HashSet<DVC_VOUCHER>();
        }
    
        public string MaDVC { get; set; }
        public string MaChuCuaHang { get; set; }
        public Nullable<int> TrangThaiVanChuyen { get; set; }
        public string TenNguoiNhan { get; set; }
        public string DiaChi { get; set; }
        public string ThanhPho { get; set; }
        public string Quan { get; set; }
        public string Phuong { get; set; }
        public string SDT { get; set; }
        public string GhiChu { get; set; }
        public double TienThuHo { get; set; }
        public double TongTienCuoc { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
    
        public virtual CHUCUAHANG CHUCUAHANG { get; set; }
        public virtual TRANGTHAIDVC TRANGTHAIDVC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HANGHOA> HANGHOAs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VANCHUYEN> VANCHUYENs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVC_VOUCHER> DVC_VOUCHER { get; set; }
        public string getDiaChi()
        {
            string diachi = "" + DiaChi + ", " + Quan + ", " + Phuong + ", " + ThanhPho;
            return diachi;
        }
    }
}
