//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANGHOA
    {
        public int MaCTDVC { get; set; }
        public string MaChuCuaHang { get; set; }
        public string MaDVC { get; set; }
        public string TenHangHoa { get; set; }
        public int SoLuong { get; set; }
        public double KhoiLuong { get; set; }
        public double GiaTri { get; set; }
    
        public virtual CHUCUAHANG CHUCUAHANG { get; set; }
        public virtual DONVANCHUYEN DONVANCHUYEN { get; set; }
    }
}
