//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VANCHUYEN
    {
        public int id { get; set; }
        public string MaDVC { get; set; }
        public Nullable<int> MaShipper { get; set; }
        public Nullable<int> MaLoaiVC { get; set; }
        public Nullable<System.DateTime> NgayGio { get; set; }
    
        public virtual DONVANCHUYEN DONVANCHUYEN { get; set; }
        public virtual LOAIVANCHUYEN LOAIVANCHUYEN { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
    }
}
