//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VOUCHER
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VOUCHER()
        {
            this.DVC_VOUCHER = new HashSet<DVC_VOUCHER>();
        }
    
        public int id { get; set; }
        public string code { get; set; }
        public string moTa { get; set; }
        public Nullable<double> phanTram { get; set; }
        public Nullable<double> toiDa { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DVC_VOUCHER> DVC_VOUCHER { get; set; }
    }
}
