//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CongTyVanChuyenEntities : DbContext
    {
        public CongTyVanChuyenEntities()
            : base("name=CongTyVanChuyenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDVC> CHITIETDVCs { get; set; }
        public virtual DbSet<CHUCUAHANG> CHUCUAHANGs { get; set; }
        public virtual DbSet<DONVANCHUYEN> DONVANCHUYENs { get; set; }
        public virtual DbSet<KHOHANG> KHOHANGs { get; set; }
        public virtual DbSet<LOAIPHIEU> LOAIPHIEUx { get; set; }
        public virtual DbSet<LOAIVANCHUYEN> LOAIVANCHUYENs { get; set; }
        public virtual DbSet<LOGINNV> LOGINNVs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAPXUATKHO> PHIEUNHAPXUATKHOes { get; set; }
        public virtual DbSet<SHIPPER> SHIPPERs { get; set; }
        public virtual DbSet<THONGKE_HETHONG> THONGKE_HETHONG { get; set; }
        public virtual DbSet<THONGTINWEBSITE> THONGTINWEBSITEs { get; set; }
        public virtual DbSet<TRANGTHAIDVC> TRANGTHAIDVCs { get; set; }
        public virtual DbSet<VANCHUYEN> VANCHUYENs { get; set; }
    }
}
