//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CongTyVanChuyen.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIEUNHAPXUATKHO
    {
        public int MaPhieu { get; set; }
        public Nullable<int> MaLoaiPhieu { get; set; }
        public Nullable<int> MaKho { get; set; }
        public Nullable<int> MaShipper { get; set; }
        public Nullable<System.DateTime> NgayNhapXuat { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KHOHANG KHOHANG { get; set; }
        public virtual LOAIPHIEU LOAIPHIEU { get; set; }
        public virtual SHIPPER SHIPPER { get; set; }
    }
}
